// ============================================================
// App Registry — All 54 Apps
// ============================================================

import type { AppDefinition } from '@/types';

export const APP_REGISTRY: AppDefinition[] = [
  // ======== SYSTEM (7) ========
  {
    id: 'filemanager',
    name: 'File Manager',
    icon: 'Folder',
    category: 'System',
    description: 'Browse, manage, and organize files and folders',
    defaultSize: { width: 800, height: 550 },
    minSize: { width: 400, height: 300 },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    category: 'System',
    description: 'Command-line interface with bash-like commands',
    defaultSize: { width: 700, height: 450 },
    minSize: { width: 400, height: 250 },
  },
  {
    id: 'texteditor',
    name: 'Text Editor',
    icon: 'FileText',
    category: 'System',
    description: 'Simple text editor with syntax highlighting',
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 320, height: 240 },
  },
  {
    id: 'calculator',
    name: 'Calculator',
    icon: 'Calculator',
    category: 'System',
    description: 'Scientific calculator with history',
    defaultSize: { width: 340, height: 480 },
    minSize: { width: 280, height: 400 },
  },
  {
    id: 'settings',
    name: 'System Settings',
    icon: 'Settings',
    category: 'System',
    description: 'System preferences and configuration',
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'systemmonitor',
    name: 'System Monitor',
    icon: 'Activity',
    category: 'System',
    description: 'CPU, memory, disk, and network monitoring',
    defaultSize: { width: 680, height: 480 },
    minSize: { width: 400, height: 300 },
  },
  {
    id: 'archivemanager',
    name: 'Archive Manager',
    icon: 'Package',
    category: 'System',
    description: 'Create and extract ZIP, TAR, 7Z archives',
    defaultSize: { width: 560, height: 420 },
    minSize: { width: 360, height: 280 },
  },

  // ======== PRODUCTIVITY (10) ========
  {
    id: 'calendar',
    name: 'Calendar',
    icon: 'Calendar',
    category: 'Productivity',
    description: 'Monthly/weekly calendar with events',
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 400, height: 360 },
  },
  {
    id: 'notes',
    name: 'Notes',
    icon: 'StickyNote',
    category: 'Productivity',
    description: 'Rich text notes with folders',
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 360, height: 300 },
  },
  {
    id: 'todo',
    name: 'Todo List',
    icon: 'CheckSquare',
    category: 'Productivity',
    description: 'Task management with priorities',
    defaultSize: { width: 480, height: 560 },
    minSize: { width: 320, height: 400 },
  },
  {
    id: 'clock',
    name: 'Clock',
    icon: 'Clock',
    category: 'Productivity',
    description: 'World clock, alarms, timer, stopwatch',
    defaultSize: { width: 440, height: 400 },
    minSize: { width: 320, height: 280 },
  },
  {
    id: 'spreadsheet',
    name: 'Spreadsheet',
    icon: 'Table2',
    category: 'Productivity',
    description: 'Basic spreadsheet with formulas',
    defaultSize: { width: 800, height: 560 },
    minSize: { width: 480, height: 320 },
  },
  {
    id: 'documentviewer',
    name: 'Document Viewer',
    icon: 'File',
    category: 'Productivity',
    description: 'PDF and document viewer',
    defaultSize: { width: 720, height: 600 },
    minSize: { width: 400, height: 360 },
  },
  {
    id: 'reminders',
    name: 'Reminders',
    icon: 'Bell',
    category: 'Productivity',
    description: 'Time-based reminders and notifications',
    defaultSize: { width: 440, height: 480 },
    minSize: { width: 320, height: 360 },
  },
  {
    id: 'contacts',
    name: 'Contacts',
    icon: 'Users',
    category: 'Productivity',
    description: 'Contact management with search',
    defaultSize: { width: 560, height: 480 },
    minSize: { width: 360, height: 320 },
  },
  {
    id: 'passwordmanager',
    name: 'Password Manager',
    icon: 'Lock',
    category: 'Productivity',
    description: 'Secure password storage',
    defaultSize: { width: 520, height: 440 },
    minSize: { width: 360, height: 300 },
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    icon: 'Layout',
    category: 'Productivity',
    description: 'Infinite canvas for sketches',
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 480, height: 360 },
  },

  // ======== INTERNET (7) ========
  {
    id: 'browser',
    name: 'Web Browser',
    icon: 'Globe',
    category: 'Internet',
    description: 'Lightweight browser with tabs and bookmarks',
    defaultSize: { width: 960, height: 640 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'email',
    name: 'Email',
    icon: 'Mail',
    category: 'Internet',
    description: 'Email client with inbox and compose',
    defaultSize: { width: 880, height: 600 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'chat',
    name: 'Chat',
    icon: 'MessageSquare',
    category: 'Internet',
    description: 'Instant messaging interface',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 320, height: 400 },
  },
  {
    id: 'weather',
    name: 'Weather',
    icon: 'CloudSun',
    category: 'Internet',
    description: 'Weather forecast with locations',
    defaultSize: { width: 440, height: 520 },
    minSize: { width: 320, height: 400 },
  },
  {
    id: 'rssreader',
    name: 'RSS Reader',
    icon: 'Rss',
    category: 'Internet',
    description: 'Feed reader for news subscriptions',
    defaultSize: { width: 800, height: 560 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'ftpclient',
    name: 'FTP Client',
    icon: 'Server',
    category: 'Internet',
    description: 'File transfer protocol client',
    defaultSize: { width: 680, height: 480 },
    minSize: { width: 400, height: 320 },
  },
  {
    id: 'networktools',
    name: 'Network Tools',
    icon: 'Wifi',
    category: 'Internet',
    description: 'Ping, traceroute, port scanner',
    defaultSize: { width: 600, height: 440 },
    minSize: { width: 400, height: 300 },
  },

  // ======== MEDIA (7) ========
  {
    id: 'musicplayer',
    name: 'Music Player',
    icon: 'Music',
    category: 'Media',
    description: 'Audio player with playlist and visualization',
    defaultSize: { width: 520, height: 440 },
    minSize: { width: 360, height: 320 },
  },
  {
    id: 'videoplayer',
    name: 'Video Player',
    icon: 'PlayCircle',
    category: 'Media',
    description: 'Video player with controls',
    defaultSize: { width: 640, height: 440 },
    minSize: { width: 400, height: 280 },
  },
  {
    id: 'imageviewer',
    name: 'Image Viewer',
    icon: 'Image',
    category: 'Media',
    description: 'Image viewer with zoom and slideshow',
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 400, height: 320 },
  },
  {
    id: 'photoeditor',
    name: 'Photo Editor',
    icon: 'Camera',
    category: 'Media',
    description: 'Basic photo editing with filters',
    defaultSize: { width: 880, height: 600 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'voicerecorder',
    name: 'Voice Recorder',
    icon: 'Mic',
    category: 'Media',
    description: 'Audio recording and playback',
    defaultSize: { width: 440, height: 320 },
    minSize: { width: 320, height: 240 },
  },
  {
    id: 'screenrecorder',
    name: 'Screen Recorder',
    icon: 'Video',
    category: 'Media',
    description: 'Screen capture and recording',
    defaultSize: { width: 520, height: 360 },
    minSize: { width: 360, height: 280 },
  },
  {
    id: 'mediaconverter',
    name: 'Media Converter',
    icon: 'RefreshCw',
    category: 'Media',
    description: 'Convert between media formats',
    defaultSize: { width: 560, height: 400 },
    minSize: { width: 360, height: 280 },
  },

  // ======== GAMES (11) ========
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    icon: 'Bomb',
    category: 'Games',
    description: 'Classic minesweeper with 3 difficulty levels',
    defaultSize: { width: 360, height: 440 },
    minSize: { width: 280, height: 360 },
  },
  {
    id: 'snake',
    name: 'Snake',
    icon: 'Gamepad2',
    category: 'Games',
    description: 'Classic snake game with increasing speed',
    defaultSize: { width: 440, height: 480 },
    minSize: { width: 320, height: 360 },
  },
  {
    id: 'tetris',
    name: 'Tetris',
    icon: 'Grid3x3',
    category: 'Games',
    description: 'Block-stacking puzzle game',
    defaultSize: { width: 400, height: 560 },
    minSize: { width: 280, height: 440 },
  },
  {
    id: 'tictactoe',
    name: 'Tic-Tac-Toe',
    icon: 'X',
    category: 'Games',
    description: '2-player and AI tic-tac-toe',
    defaultSize: { width: 400, height: 440 },
    minSize: { width: 280, height: 320 },
  },
  {
    id: 'game2048',
    name: '2048',
    icon: 'Hash',
    category: 'Games',
    description: 'Number sliding puzzle',
    defaultSize: { width: 400, height: 480 },
    minSize: { width: 320, height: 400 },
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    icon: 'Grid2x2',
    category: 'Games',
    description: '9x9 number puzzle with 4 difficulties',
    defaultSize: { width: 480, height: 520 },
    minSize: { width: 360, height: 400 },
  },
  {
    id: 'chess',
    name: 'Chess',
    icon: 'Crown',
    category: 'Games',
    description: 'Chess with AI opponent',
    defaultSize: { width: 560, height: 600 },
    minSize: { width: 400, height: 440 },
  },
  {
    id: 'memory',
    name: 'Memory Game',
    icon: 'Brain',
    category: 'Games',
    description: 'Card matching memory game',
    defaultSize: { width: 480, height: 440 },
    minSize: { width: 320, height: 280 },
  },
  {
    id: 'pong',
    name: 'Pong',
    icon: 'Circle',
    category: 'Games',
    description: 'Classic paddle ball game',
    defaultSize: { width: 600, height: 400 },
    minSize: { width: 400, height: 280 },
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    icon: 'Layers',
    category: 'Games',
    description: 'Classic card solitaire',
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'flappybird',
    name: 'Flappy Bird',
    icon: 'Feather',
    category: 'Games',
    description: 'Side-scrolling arcade game',
    defaultSize: { width: 400, height: 560 },
    minSize: { width: 280, height: 400 },
  },

  // ======== DEV TOOLS (8) ========
  {
    id: 'codeeditor',
    name: 'Code Editor',
    icon: 'Code2',
    category: 'DevTools',
    description: 'Syntax-highlighted code editor with tabs',
    defaultSize: { width: 880, height: 640 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'jsonformatter',
    name: 'JSON Formatter',
    icon: 'Braces',
    category: 'DevTools',
    description: 'Format, validate, and beautify JSON',
    defaultSize: { width: 680, height: 520 },
    minSize: { width: 400, height: 320 },
  },
  {
    id: 'regextester',
    name: 'Regex Tester',
    icon: 'Search',
    category: 'DevTools',
    description: 'Test and debug regular expressions',
    defaultSize: { width: 720, height: 480 },
    minSize: { width: 440, height: 320 },
  },
  {
    id: 'markdownpreview',
    name: 'Markdown Preview',
    icon: 'FileCode',
    category: 'DevTools',
    description: 'Live markdown preview with GitHub styling',
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'gitclient',
    name: 'Git Client',
    icon: 'GitBranch',
    category: 'DevTools',
    description: 'Git repository visualization',
    defaultSize: { width: 880, height: 600 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'apitester',
    name: 'API Tester',
    icon: 'Send',
    category: 'DevTools',
    description: 'REST API testing with HTTP methods',
    defaultSize: { width: 720, height: 560 },
    minSize: { width: 440, height: 360 },
  },
  {
    id: 'base64tool',
    name: 'Base64 Tool',
    icon: 'Shuffle',
    category: 'DevTools',
    description: 'Encode/decode Base64 and URL strings',
    defaultSize: { width: 560, height: 440 },
    minSize: { width: 360, height: 300 },
  },
  {
    id: 'colorpalette',
    name: 'Color Palette',
    icon: 'Palette',
    category: 'DevTools',
    description: 'Color schemes and palette generation',
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 400, height: 320 },
  },

  // ======== CREATIVE (4) ========
  {
    id: 'drawing',
    name: 'Drawing',
    icon: 'Paintbrush',
    category: 'Creative',
    description: 'Canvas-based drawing with brushes',
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'colorpicker',
    name: 'Color Picker',
    icon: 'Pipette',
    category: 'Creative',
    description: 'Pick colors from anywhere, generate palettes',
    defaultSize: { width: 440, height: 400 },
    minSize: { width: 320, height: 280 },
  },
  {
    id: 'imagegallery',
    name: 'Image Gallery',
    icon: 'Images',
    category: 'Creative',
    description: 'Browse and organize image collections',
    defaultSize: { width: 800, height: 560 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: 'asciiart',
    name: 'ASCII Art',
    icon: 'Type',
    category: 'Creative',
    description: 'Create ASCII text art and diagrams',
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 400, height: 320 },
  },
];

export const getAppById = (id: string): AppDefinition | undefined =>
  APP_REGISTRY.find((a) => a.id === id);

export const getAppsByCategory = (category: string): AppDefinition[] =>
  APP_REGISTRY.filter((a) => a.category === category);

export const getDefaultDockApps = (): string[] => [
  'filemanager',
  'terminal',
  'texteditor',
  'browser',
  'settings',
];
